### ISSUE TITLE
serveStatic isn't working

### ISSUE THREAD

**Issue by ibnumusyaffa** [honojs/node-server#118]
serve static is not working, iam not using absolute path, minimal repro https://github.com/ibnumusyaffa/hono-serve-static-not-working

**Comment by ibnumusyaffa** [comment]
![image](https://github.com/honojs/node-server/assets/19760223/118dc862-b755-4b5c-8311-8db1656f6072)

**Comment by yusukebe** [comment]
Hi @ibnumusyaffa 

Thank you for creating the issue.

You can do what you want to do with the following code:

```ts
app.get(
  "/static/*",
  serveStatic({
    root: "./storage",
    rewriteRequestPath: (path: string) => path.replace(/^\/static/, ""),
  })
)
```

I would like to introduce [`onNotFound()`](https://github.com/honojs/hono/pull/1825) because the current implementation of `@hono/node-server` is difficult to debug when a file is not found.

**Comment by yusukebe** [comment]
This can be closed. Thanks!
